{
    "topic": "TS LF Trading Bot Errors",
    "pageNumber": 51,
    "type": "TS LF Trading Bot Error - Snapshot Instruction Evaluation Error",
    "definition": {
        "text": "This error occured while evaluating an instruction as part of the process of generating a Snapshot. This did not prevent the Snapshot from being created, but the value for the particular instruction was set to zero.",
        "updated": 1611949667634
    },
    "paragraphs": [
        {
            "style": "Error",
            "text": "Snapshot Instruction Evaluation Error",
            "updated": 1611681105978
        },
        {
            "style": "Title",
            "text": "Error Info"
        },
        {
            "style": "Text",
            "text": "In the following section, you will find the information recorded when the error occurred."
        },
        {
            "style": "Note",
            "text": "You will only see the information if you opened this page as a result of the error actually occurring."
        },
        {
            "style": "Subtitle",
            "text": "Error Message"
        },
        {
            "style": "Text",
            "text": "The following is the Error Message of the Exception that occured at the LF Trading Bot:"
        },
        {
            "style": "Placeholder",
            "text": "errorMessage"
        },
        {
            "style": "Subtitle",
            "text": "Error Stack"
        },
        {
            "style": "Text",
            "text": "The following is the Error Stack of the Exception that occured at the LF Trading Bot:"
        },
        {
            "style": "Placeholder",
            "text": "errorStack"
        },
        {
            "style": "Subtitle",
            "text": "Error Code"
        },
        {
            "style": "Text",
            "text": "The following is the Error Code of the Exception that occured at the LF Trading Bot:"
        },
        {
            "style": "Placeholder",
            "text": "errorCode"
        },
        {
            "style": "Subtitle",
            "text": "Error Details"
        },
        {
            "style": "Text",
            "text": "The following are all the Error details of the Exception that occured at the LF Trading Bot:"
        },
        {
            "style": "Placeholder",
            "text": "errorDetails"
        },
        {
            "style": "Subtitle",
            "text": "Node Name"
        },
        {
            "style": "Text",
            "text": "The following is the node's name of the Node most related to this error:"
        },
        {
            "style": "Placeholder",
            "text": "nodeName"
        },
        {
            "style": "Subtitle",
            "text": "Node Code"
        },
        {
            "style": "Text",
            "text": "The following is the code stored at the node that produced the error at the LF Trading Bot:"
        },
        {
            "style": "Placeholder",
            "text": "nodeCode"
        },
        {
            "style": "Subtitle",
            "text": "Context Info",
            "updated": 1611681195733
        },
        {
            "style": "Text",
            "text": "The following is the context information preserved when the error occured:",
            "updated": 1611681225358
        },
        {
            "style": "Placeholder",
            "text": "contextInfo",
            "updated": 1611681233411
        },
        {
            "style": "Text",
            "text": ""
        }
    ]
}